# Generated by Django 4.1.3 on 2023-02-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon_detailproduct_orderitem_productimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categorie'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='image',
            field=models.ImageField(blank=True, default='images_coupon/coupon.png', null=True, upload_to='images_coupon'),
        ),
    ]
