# Generated by Django 4.1.2 on 2022-10-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_image_delete_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
