# Generated by Django 4.1.2 on 2022-10-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_image_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
