# Generated by Django 4.1.2 on 2022-10-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_image_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
