# Generated by Django 4.1.2 on 2022-11-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
