# Generated by Django 4.1.2 on 2022-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
