# Generated by Django 4.1.2 on 2022-11-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
