version: '3'
 
services:
  django:
        build: .
        container_name: django
        command: >
          sh -c "python manage.py wait_for_db &&
                 python manage.py migrate &&
                 python manage.py loaddata fixtures/Category.json &&
                 python manage.py loaddata fixtures/Customer.json &&
                 python manage.py loaddata fixtures/Product.json &&
                 python manage.py runserver 0.0.0.0:8000" 

        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - db
            - redis
 
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
  celery:
    restart: always
    environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
    build: .
    command: celery -A ecommerce worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - django
  celery-beat:
      restart: always
      environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
      build: .
      command: celery -A ecommerce beat -l info
      volumes:
        - .:/usr/src/app/
      depends_on:
        - redis
        - django
  redis:
    image: "redis:alpine"
volumes:
  pgdata:

# version: "3.11"
   
# services:
#     django:
#         build: .
#         container_name: django
#         command: python manage.py runserver 0.0.0.0:8000
#         volumes:
#             - .:/usr/src/app/
#         ports:
#             - "8000:8000"
#         environment:
#             - DEBUG=1
#             - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#             - CELERY_BROKER=redis://redis:6379/0
#             - CELERY_BACKEND=redis://redis:6379/0
#         depends_on:
#             - redis
#     celery:
#         build: .
#         command: celery -A ecommerce.celery worker --pool=solo  -l info
#         volumes:
#             - .:/usr/src/app
#         environment:
#             - DEBUG=1
#             - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#             - CELERY_BROKER=redis://redis:6379/0
#             - CELERY_BACKEND=redis://redis:6379/0
#         depends_on:
#             - django
#             - redis
#     celery-beat:
#         build: .
#         command: celery -A ecommerce beat -l INFO
#         volumes:
#             - .:/usr/src/app
#         depends_on:
#             - redis
#         environment:
#             - DEBUG=1
#             - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#             - CELERY_BROKER=redis://redis:6379/0
#             - CELERY_BACKEND=redis://redis:6379/0
#     redis:
#         image: "redis:alpine"
        
# volumes:
#     pgdata: