version: '3'
 
services:
  django:
        build: .
        container_name: django
        command: >
          sh -c "python manage.py wait_for_db &&
                 python manage.py runserver 0.0.0.0:8000" 
        volumes:
            - .:/usr/src/app/
        expose:
            - 8000
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=*
            - CELERY_BROKER=redis://redis-19334.c12.us-east-1-4.ec2.cloud.redislabs.com:19334
            - CELERY_BACKEND=redis://redis-19334.c12.us-east-1-4.ec2.cloud.redislabs.com:19334
        depends_on:
            - db
            - redis
 
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
  celery:
    restart: always
    environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=*
            - CELERY_BROKER=redis://default:6yIhwXmpa4vFgJEvqATt@containers-us-west-127.railway.app:6967
            - CELERY_BACKEND=redis://default:6yIhwXmpa4vFgJEvqATt@containers-us-west-127.railway.app:6967
    build: .
    command: celery -A ecommerce worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - django
  celery-beat:
      restart: always
      environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=*
            - CELERY_BROKER=redis://default:6yIhwXmpa4vFgJEvqATt@containers-us-west-127.railway.app:6967
            - CELERY_BACKEND=redis://default:6yIhwXmpa4vFgJEvqATt@containers-us-west-127.railway.app:6967
      build: .
      command: celery -A ecommerce beat -l info
      volumes:
        - .:/usr/src/app/
      depends_on:
        - redis
        - django
  redis:
    image: "redis:alpine"
volumes:
  pgdata:

# docker compose expose ports, create EC2 and git clone repo, mapping ports, docker-compose up -d