# Generated by Django 4.1.3 on 2023-01-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='images_customer/default.png', upload_to='images_customer'),
        ),
    ]
