# Generated by Django 4.1.2 on 2022-11-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_age_customer_sex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
