# Generated by Django 4.1.2 on 2022-12-01 01:58

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('countries', django_countries.fields.CountryField(max_length=2)),
                ('mobilephone', models.CharField(default=None, max_length=20)),
            ],
            options={
                'verbose_name': 'BillingAddress',
                'db_table': 'billing_address',
            },
        ),
    ]
