# Generated by Django 4.1.2 on 2022-11-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_user_billingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='mobilephone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
