# Generated by Django 4.1.2 on 2022-11-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
