# Generated by Django 4.1.2 on 2022-10-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_comment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
