# Generated by Django 4.1.2 on 2022-10-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_comment_options_alter_comment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
