# Generated by Django 4.1.2 on 2022-10-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='orderdetail',
        ),
    ]
