# Generated by Django 4.1.2 on 2022-10-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_table_alter_orderdetail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table=None,
        ),
    ]
