# Generated by Django 4.1.2 on 2022-10-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_table_alter_orderdetail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='orderdetail',
        ),
    ]
