# Generated by Django 4.1.2 on 2022-11-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
