# Generated by Django 4.1.2 on 2022-11-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
